# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
  
# SITE CONFIGURATION
baseurl: "/"
url: "https://jbruslind.github.io"

# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            HyperRail
tagline:          'Automated Greenhouse Analysis'
description:      'An automated gantry system to perform hyperspectral imaging of greenhouse / growing areas'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jorian Bruslind'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Jbruslind/PersonalProjects/tree/master/HyperRail
