# Dependencies
markdown:         kramdown
highlighter:      pygments
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            HyperRail
tagline:          'Automated Greenhouse Analysis'
description:      'An automated gantry system to preform hyperspectral imaging of greenhouse / growing areas'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jorian Bruslind'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Jbruslind/PersonalProjects/tree/master/HyperRail
